/*
	Code generated by config2go(https://github.com/xylonx/config2go)
	DON EDIT!
*/
package config

type Setting struct {
	Application struct {
		CronjobPoolSize int64 `mapstructure:"cronjob_pool_size" json:"cronjob_pool_size" yaml:"cronjob_pool_size" `
	} `mapstructure:"application" json:"application" yaml:"application" `
	CryptoCoin struct {
		ApiKey string `mapstructure:"api_key" json:"api_key" yaml:"api_key" `
	} `mapstructure:"crypto_coin" json:"crypto_coin" yaml:"crypto_coin" `
	Picture struct {
		General struct {
			Type string `mapstructure:"type" json:"type" yaml:"type" `
		} `mapstructure:"general" json:"general" yaml:"general" `
		Pornographic struct {
			Local struct {
				Dir string `mapstructure:"dir" json:"dir" yaml:"dir" `
			} `mapstructure:"local" json:"local" yaml:"local" `
			Type string `mapstructure:"type" json:"type" yaml:"type" `
		} `mapstructure:"pornographic" json:"pornographic" yaml:"pornographic" `
		Sync bool `mapstructure:"sync" json:"sync" yaml:"sync" `
	} `mapstructure:"picture" json:"picture" yaml:"picture" `
	TelegramBot struct {
		ApiKey string `mapstructure:"api_key" json:"api_key" yaml:"api_key" `
	} `mapstructure:"telegram_bot" json:"telegram_bot" yaml:"telegram_bot" `
}
